services:
    portal-frontend:
        image: portal-frontend
        build:
            context: .
        container_name: portal-frontend
        restart: unless-stopped
        networks:
            - app-network
        environment:
            AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
            AUTH0_SECRET: ${AUTH0_SECRET}
