services:
  portal-backend:
    build:
      context: .
    container_name: portal-backend
    restart: unless-stopped
    command: >
      sh -c 'python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000'
    env_file:
      - /home/ubuntu/data/env/portal-backend/prod.env
    networks:
      - app-network
